In [1]:
!pip install mlxtend
import numpy as np
import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: mlxtend in c:\users\science\appdata\roaming\python\python311\site-packages (0.23.1)
Requirement already satisfied: scipy>=1.2.1 in c:\programdata\anaconda3\lib\site-packages (from mlxtend) (1.11.1)
Requirement already satisfied: numpy>=1.16.2 in c:\programdata\anaconda3\lib\site-packages (from mlxtend) (1.24.3)
Requirement already satisfied: pandas>=0.24.2 in c:\programdata\anaconda3\lib\site-packages (from mlxtend) (2.0.3)
Requirement already satisfied: scikit-learn>=1.0.2 in c:\programdata\anaconda3\lib\site-packages (from mlxtend) (1.3.0)
Requirement already satisfied: matplotlib>=3.0.0 in c:\programdata\anaconda3\lib\site-packages (from mlxtend) (3.7.2)
Requirement already satisfied: joblib>=0.13.2 in c:\programdata\anaconda3\lib\site-packages (from mlxtend) (1.2.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.0.5)
Requirement already satisfied: cycler>=0.10 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (23.1)
Requirement already satisfied: pillow>=6.2.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (9.4.0)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\programdata\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2023.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\programdata\anaconda3\lib\site-packages (from scikit-learn>=1.0.2->mlxtend) (2.2.0)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.16.0)

In [2]:
df = pd.read_csv("C:/Users/SCIENCE/Documents/market1.csv")
df

,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
0,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7495,butter,light mayo,fresh bread,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7496,burgers,frozen vegetables,eggs,french fries,magazines,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7497,chicken,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7498,escalope,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7499,eggs,frozen smoothie,yogurt cake,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
items=df.columns
items

Index(['shrimp', 'almonds', 'avocado', 'vegetables mix', 'green grapes',
       'whole weat flour', 'yams', 'cottage cheese', 'energy drink',
       'tomato juice', 'low fat yogurt', 'green tea', 'honey', 'salad',
       'mineral water', 'salmon', 'antioxydant juice', 'frozen smoothie',
       'spinach', 'olive oil'],
      dtype='object')

In [4]:
encoded_vals = []
for index, row in df.iterrows(): 
    labels = {}
    uncommons = list(set(items) - set(row))
    commons = list(set(items).intersection(row))
    for uc in uncommons:
        labels[uc] = 0
    for com in commons:
        labels[com] = 1
    encoded_vals.append(labels)

In [5]:
ohe_df = pd.DataFrame(encoded_vals)
ohe_df

,yams,green grapes,frozen smoothie,avocado,salad,energy drink,almonds,mineral water,whole weat flour,spinach,olive oil,vegetables mix,cottage cheese,green tea,low fat yogurt,shrimp,tomato juice,honey,salmon,antioxydant juice
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7495,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7496,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
7497,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7498,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
7499,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0

In [6]:
freq_items = apriori(ohe_df, min_support = 0.002, use_colnames = True, verbose = 1)
freq_items

C:\Users\SCIENCE\AppData\Roaming\Python\Python311\site-packages\mlxtend\frequent_patterns\fpcommon.py:109: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

Processing 196 combinations | Sampling itemset size 4

      support                                  itemsets
0    0.011333                                    (yams)
1    0.008933                            (green grapes)
2    0.063200                         (frozen smoothie)
3    0.033200                                 (avocado)
4    0.004800                                   (salad)
..        ...                                       ...
107  0.002667        (mineral water, green tea, shrimp)
108  0.002533  (mineral water, tomato juice, green tea)
109  0.002667         (mineral water, honey, green tea)
110  0.002533        (salmon, mineral water, green tea)
111  0.002400           (salmon, mineral water, shrimp)

[112 rows x 2 columns]

In [14]:
sort1 = association_rules(freq_items, metric = "confidence", min_threshold = 0.006)
sort1.sort_values("confidence", ascending= False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
212,"(olive oil, shrimp)",(mineral water),0.008000,0.238267,0.004400,0.550000,2.308338,0.002494,1.692741,0.571359
247,"(salmon, shrimp)",(mineral water),0.004533,0.238267,0.002400,0.529412,2.221930,0.001320,1.618683,0.552445
217,"(salmon, olive oil)",(mineral water),0.005600,0.238267,0.002533,0.452381,1.898633,0.001199,1.390991,0.475971
241,"(salmon, green tea)",(mineral water),0.005733,0.238267,0.002533,0.441860,1.854479,0.001167,1.364772,0.463422
186,"(salmon, frozen smoothie)",(mineral water),0.004933,0.238267,0.002133,0.432432,1.814909,0.000958,1.342102,0.451234
...,...,...,...,...,...,...,...,...,...,...
250,(mineral water),"(salmon, shrimp)",0.238267,0.004533,0.002400,0.010073,2.221930,0.001320,1.005596,0.721960
172,(mineral water),"(frozen smoothie, low fat yogurt)",0.238267,0.007200,0.002133,0.008954,1.243549,0.000418,1.001769,0.257111
191,(mineral water),"(salmon, frozen smoothie)",0.238267,0.004933,0.002133,0.008954,1.814909,0.000958,1.004057,0.589456
195,(mineral water),"(green tea, almonds)",0.238267,0.004933,0.002000,0.008394,1.701478,0.000825,1.003490,0.541233
160,(mineral water),"(frozen smoothie, cottage cheese)",0.238267,0.004800,0.002000,0.008394,1.748741,0.000856,1.003624,0.562086

In [33]:
p=association_rules(freq_items, metric = "confidence", min_threshold = 0.006)
Newconfidence=p["confidence"] * 100
Newconfidence

0      30.588235
1       1.454952
2       1.287073
3      34.328358
4      14.859438
         ...
247    52.941176
248    10.227273
249     5.660377
250     1.007275
251     3.364486
Name: confidence, Length: 252, dtype: float64

In [34]:
newlift=np.round(p["lift"])
newlift

0      1.0
1      1.0
2      1.0
3      1.0
4      2.0
      ...
247    2.0
248    2.0
249    2.0
250    2.0
251    2.0
Name: lift, Length: 252, dtype: float64

In [ ]:
)